### PR TITLE
Refactoring unwrap and handling errors

### PR DESCRIPTION
**Pull request by kevin-valerio**
Please, see https://github.com/multiformats/rust-multihash/issues/282 for more informations

### CODE REVIEW

**Review by vmx — COMMENTED** [review]
It would be great to have a test with the malicious payload, to make sure we won't have a regression in the future.

**Comment by mattheworris** [comment]
> It would be great to have a test with the malicious payload, to make sure we won't have a regression in the future.

I attempted to create a test, but I could not get the test to work properly in a no-std environment.

**Comment by kevin-valerio** [comment]
> > It would be great to have a test with the malicious payload, to make sure we won't have a regression in the future.
> 
> I attempted to create a test, but I could not get the test to work properly in a no-std environment.

See [that link](https://github.com/multiformats/rust-multihash/issues/282#issuecomment-1485130230), I wrote a test there with the good Cargo.toml config to reproduce the bug.

**Comment by mattheworris** [comment]
> > > It would be great to have a test with the malicious payload, to make sure we won't have a regression in the future.
> > 
> > 
> > I attempted to create a test, but I could not get the test to work properly in a no-std environment.
> 
> See [that link](https://github.com/multiformats/rust-multihash/issues/282#issuecomment-1485130230), I wrote a test there with the good Cargo.toml config to reproduce the bug.

To clarify, I could not create a test that would work with `cargo test` in this repo. 
Regardless of what I tried (`--no-default-features` flags, etc.), `std` was always defined.

**Comment by thomaseizinger** [comment]
Replaced by https://github.com/multiformats/rust-multihash/pull/291.

**Pull request closed without merging**
