### PR TITLE
fix: upgrade syn and synstructure (#362)

### LINKED ISSUE #362: updating dependencies on syn and synstructure.
Hi.

I'm one of the Debian rust maintainers, and I'm currently looking at the update of rust-syn to version 2.0 and rust-synstructure to version 0.18.

After bumping the dependency the multihash-derive-impl crate fails to build with

     error[E0609]: no field `tokens` on type `&Attribute`
        --> src/multihash.rs:100:74
         |
     100 |             let attr: Result<utils::Attrs<MhAttr>, _> = syn::parse2(attr.tokens.clone());
     | ^^^^^^ unknown field
        |
        = note: available fields are: `pound_token`, `style`, `bracket_token`, `meta`
   
     error[E0609]: no field `tokens` on type `&Attribute`
        --> src/multihash.rs:141:82
         |
     141 |         let derive_attrs: Result<utils::Attrs<DeriveAttr>, _> = syn::parse2(attr.tokens.clone());
     | ^^^^^^ unknown field
         |
          = note: available fields are: `pound_token`, `style`, `bracket_token`, `meta`
    
     error[E0061]: this method takes 2 arguments but 1 argument was supplied
        --> src/utils.rs:25:29
         |
     25  |         let attrs = content.parse_terminated(A::parse)?;
         |                             ^^^^^^^^^^^^^^^^---------- an argument is missing
        | 

Is there any chance of an update/patch to use the current versions of syn/synstructure?

### PR DESCRIPTION
**Pull request by jmg-duarte**
fixes #362
closes #350 
closes #301 

* I've added an `Ident` to `utils::Attrs` since `attr.meta.to_token_stream()` now includes it.
* I've also removed `ParseError` since it didn't seem to be used (and tests seemed to passed)

### CODE REVIEW

**Comment by jmg-duarte** [comment]
@vmx tests fail against stable but pass against 1.77, let me know which one should I target

**Comment by jmg-duarte** [comment]
@vmx stable (1.78) has different errors to 1.77, should I change the expected errors to match or should we change CI?

Personally, when I developed macros, I would pin them against the MSRV and test against it only

**Review by vmx — COMMENTED** [review]
The rest looks good. Thanks a lot for tackling this!

**Comment by vmx** [comment]
The code coverage issue is unrelated. Feel free to ignore it and I'll make a PR for it later, or change the tarpaulin action version to `0.30.0`, which should make it work.

**Review by vmx — APPROVED** [review]
Thanks so much for this PR!

**Pull request merged**
