### PR TITLE
feat: update digest, sha-1, sha2 and sha3 to v0.9

### PR DESCRIPTION
**Pull request by koushiro**
Signed-off-by: koushiro <koushiro.cqx@gmail.com>

~~**BREAKING CHANGE**: Rename some methods in the `MultihashDigest` trait~~
    
~~`input` ==> `update`~~
~~`result` ==> `finalize`~~
~~`result_reset` ==> `finalize_reset`~~

### CODE REVIEW

**Comment by koushiro** [comment]
＠vmx PTAL

**Comment by koushiro** [comment]
@vmx PTAL

**Comment by mriise** [comment]
@vmx mind pointing me towards where that refactoring work is being done? 
I'd like to take a poke around.

**Comment by koushiro** [comment]
@vmx PTAL, I have restored the API. 
The main reason I changed the API before was to be consistent with the methods of upstream dependencies.

**Comment by vmx** [comment]
@mriise it's based around https://github.com/multiformats/rust-multihash/pull/69 / https://github.com/ipfs-rust/tiny-multihash

**Pull request merged**
