### PR TITLE
Add cli interface

### PR DESCRIPTION
**Pull request by dvc94ch**
As a well behaved unix library it should have a cli :)

### CODE REVIEW

**Comment by dvc94ch** [comment]
Also adds murmur3 support for #34

**Comment by dvc94ch** [comment]
@dignifiedquire what do you think?

**Comment by dignifiedquire** [comment]
actually there was no fix, I just improved the api, so you could just use the original version here: https://github.com/stusmall/murmur3

**Comment by vmx** [comment]
The API changed quite a bit with the release of 0.10.0 so this would need a rebase. If you still have interest in providing a CLI, please make this PR (or create a new one) with the CLI changes only and without adding the murmur hashing (that should be a separate PR).

**Comment by dvc94ch** [comment]
I'll reopen, I think it would be useful to have

**Comment by vmx** [comment]
I agree that it would be useful, thanks!

**Pull request closed without merging**
